; Proyecto firmware ESP32 - Sistema de trazabilidad de cajas de fruta (TFG)
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -D MQTT_MAX_PACKET_SIZE=512
lib_deps =
    arduino12/rdm6300@^2.0.0
    knolleary/PubSubClient@^2.8
