; Proyecto firmware ESP32 - Sistema de trazabilidad de cajas de fruta (TFG)
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    arduino12/rdm6300@^2.0.0
